name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: configure
      run: ./compile.sh KERNEL_ONLY=no BOARD=tn3399 BRANCH=current RELEASE=jammy BUILD_DESKTOP=no BUILD_MINIMAL=no KERNEL_CONFIGURE=no REPOSITORY_INSTALL="kernel,armbian-firmware" EXTERNAL_NEW=prebuilt
      
    - name: Install dependencies
      run: ls
      
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.2.1
      with:
        repo_token: ${{ secrets.YOURTOKEN }}
        file: ./optput
        tag: ${{ github.ref }}
        file_glob: true

      
  

